development: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: gestor_online_development
  username: postgres
  password:
  host: localhost

test:
  <<: *default
  database: gestor_online_test

production:
  <<: *default
  database: gestor_online
